### ISSUE TITLE
Spell text by pressing tab using JAWS on windows or screen reader on MAC

### ISSUE THREAD

**Issue by rahulr892** [open-indy/Koa11y#19]
Does this test for accessibility to spell text out loud by pressing tab using JAWS on windows or screen reader on MAC ???

Feature Request :
Also can you add support for multiple URL

**Comment by TheJaredWilcurt** [comment]
Koa11y is built on top of Pa11y, which is built on top of HTML_CodeSniffer.

* http://squizlabs.github.io/HTML_CodeSniffer/

The results that Koa11y outputs are currently limited to what is supported in those other two technologies.

* * *

Multiple URLs wouldn't be all that hard. I'd need to think about how best to implement that from a UX perspective. Currently the report's filename is based on the URL by default, but allows you to change it. I have a few ideas, but will need to give it more thought before diving in.

**Comment by TheJaredWilcurt** [comment]
Closing this issue as it has answered the original question the feature request has had it's own issue created.
