### ISSUE TITLE
Cut/Copy/Paste OSX shortcuts

### ISSUE THREAD

**Issue by TheJaredWilcurt** [open-indy/Koa11y#3]
Though Ctrl+X/Ctrl+C/Ctrl+V works fine in Windows and Linux, the Cmd+C/Cmd+X/Cmd+V need to be added manually for OSX.

This is a simple thing that should be included in the next release.

**Comment by TheJaredWilcurt** [comment]
Something like this should work:
```js
function keyBindings () {
    document.onkeydown = function (pressed) {
        // Check CMD+Shift+R and cut
        if (pressed.metaKey && pressed.shiftKey && pressed.keyCode === 82) {
                document.execCommand("cut");
                return false;
        } else if () {
                document.execCommand("copy");
                return false;
        } else if () {
                document.execCommand("paste");
                return false;
        }
    };
}
keyBindings();
```
Reference:
* http://www.asciitable.com/index/asciifull.gif

**Comment by robgaston1** [comment]
Where would this code live? In the app.js? I am working on understanding the code.

**Comment by TheJaredWilcurt** [comment]
That would be fine for now. We haven't started reorganizing and decoupling the code yet.

**Comment by TheJaredWilcurt** [comment]
Cmd+C and Cmd+V work, but to cut, you have to do Cmd+R, should be Cmd+X.

@robgaston1

**Comment by robgaston1** [comment]
Just committed a change that should have fixed cmd+x to cut

**Comment by TheJaredWilcurt** [comment]
@robgaston1 
The line that runs the keybinding function should be wrapped in an if statement to detect if you are on osx
```js
if (process.platform === 'darwin') {
    keybindingsorwhatever();
}
```

**Comment by robgaston1** [comment]
@TheJaredWilcurt I added this function wrapper. Copy, cut, and paste are all working on my local build.
