### ISSUE TITLE
Auditing pages behind logins

### ISSUE THREAD

**Issue by cycomachead** [open-indy/Koa11y#9]
It would be awesome if there were a way to audit pages behind a login. 

Perhaps, it could be possible to simply drop in a cookie that is used for the audit, or there could be some script for going to the login page first.

**Comment by TheJaredWilcurt** [comment]
Koa11y is built on top of [Pa11y](http://pa11y.org). Pa11y just got some new features recently, one of which is "actions" where you can tell it to do specific tasks before checking for accessibility issues. I need to explore these new features in more detail before I can start figuring out how to best represent them in the UI. But if I can find a way, then it most likely allow for this.

**Comment by TheJaredWilcurt** [comment]
Closing this ticket to consolidate it with #27. Once Actions are added into Koa11y, you will be able to audit pages behind logins.
